backend:
  podAnnotations:
    proxy.istio.io/config: '{"proxyMetadata":{"ISTIO_META_DNS_CAPTURE":"true","ISTIO_META_DNS_AUTO_ALLOCATE":"true"}}'
  image:
    repository: dorayakiiiiz/yas-storefront-bff
    tag: latest

  nameOverride: storefront-bff
  fullnameOverride: storefront-bff

  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,storefront-bff-extra-configmap"

  ingress:
    enabled: true
    host: storefront.dev.local.com
    path: /

  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://storefront-ui.dev.svc.cluster.local:3000
    - name: JAVA_TOOL_OPTIONS
      value: "-Djava.net.preferIPv4Stack=true -Dreactor.netty.native.useJdkDnsResolver=true"
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret
  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: storefront-bff-extra-config
      configMap:
        name: storefront-bff-extra-configmap
  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: storefront-bff-extra-config
      mountPath: /opt/yas/extra-config
  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/storefront-bff-extra-config.yaml
  hostAliases:
    - ip: "10.107.36.237"
      hostnames: ["product", "product.dev.svc.cluster.local"]
    - ip: "10.106.118.35"
      hostnames: ["cart", "cart.dev.svc.cluster.local"]
    - ip: "10.100.179.89"
      hostnames: ["customer", "customer.dev.svc.cluster.local"]
    - ip: "10.100.164.207"
      hostnames: ["inventory", "inventory.dev.svc.cluster.local"]
    - ip: "10.104.193.183"
      hostnames: ["media", "media.dev.svc.cluster.local"]
    - ip: "10.111.78.114"
      hostnames: ["order", "order.dev.svc.cluster.local"]
    - ip: "10.100.133.185"
      hostnames: ["sampledata", "sampledata.dev.svc.cluster.local"]
    - ip: "10.98.186.243"
      hostnames: ["search", "search.dev.svc.cluster.local"]
    - ip: "10.102.21.177"
      hostnames: ["tax", "tax.dev.svc.cluster.local"]
    - ip: "10.100.204.189"
      hostnames: ["keycloak-service", "keycloak-service.dev.svc.cluster.local", "identity.yas.local.com", "identity.dev.local.com"]
    - ip: "10.97.117.51"
      hostnames: ["keycloak-operator", "keycloak-operator.dev.svc.cluster.local"]
