# values-dev.yaml
envTag: "dev"
repoURL: "https://github.com/dorayakiiiiz/yas-gitops.git"
targetRevision: main # Nhánh chứa source code và Helm charts
project: default

coreServices:
  - product
  - cart
  - order
  - customer
  - inventory
  - tax
  - media
  - search
  - sampledata

services:
  yas-configuration: { tag: "latest" }
  storefront-bff: { tag: "8a39fcd" }
  storefront-ui: { tag: "6b1be46" }
  backoffice-bff: { tag: "8a39fcd" }
  backoffice-ui: { tag: "latest" }
  swagger-ui: { tag: "latest" }
  product: { tag: "latest" }
  cart: { tag: "8a39fcd" }
  order: { tag: "latest" }
  customer: { tag: "latest" }
  inventory: { tag: "latest" }
  tax: { tag: "latest" }
  media: { tag: "latest" }
  search: { tag: "latest" }
  sampledata: { tag: "latest" }
