apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ui.fullname" . }}-retry
spec:
  hosts:
    - {{ include "ui.fullname" . }}
  http:
    - retries:
        attempts: 3
        perTryTimeout: 5s
        retryOn: 5xx,gateway-error,connect-failure,retriable-4xx
      timeout: 20s
      route:
        - destination:
            host: {{ include "ui.fullname" . }}
            port:
              number: {{ .Values.service.port }}
