backend:
  image:
    repository: dorayakiiiiz/yas-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  databaseName: product

  httpPort: 8080

  ingress:
    enabled: false
  extraEnvs:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xms64m -Xmx384m -XX:MaxMetaspaceSize=256m"
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml
  serviceMonitor:
    enabled: true

